### ISSUE TITLE
Thanks for the word search code base. 

### ISSUE THREAD

**Issue by icarusfactor** [Tazeg/WordSearch#1]
I've modified your code to use PDO Mysql DB and work on Wordpress 5.x as a plugin using CSS2/3 and HTML5 and fix some of the bugs that still existed. You can view it working on my site http://www.userspace.org 
I'm still working on it , but its really solid and fast. The modified code is located at:
https://github.com/icarusfactor/userspaceorg/tree/master/Plugins/wordsquest

I may move it or the updated code to its own directory,once I get it finished.
But thanks again.

**Comment by Tazeg** [comment]
Thanks for sharing. Nice work. Don't merge here please, but it would be great to let your code available on github or anywhere.
